// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBibekW-972BMNCHJpCyHYAcVE2X5e8Tac',
    appId: '1:629374223951:web:e73d490726e2b5e7130c3a',
    messagingSenderId: '629374223951',
    projectId: 'agriconnect-9aab3',
    authDomain: 'agriconnect-9aab3.firebaseapp.com',
    storageBucket: 'agriconnect-9aab3.firebasestorage.app',
    measurementId: 'G-6L0HM639TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS4Il08j0dxxYWGhKwLrD_WR1gzZQW9gk',
    appId: '1:629374223951:android:4435d45ab3bada20130c3a',
    messagingSenderId: '629374223951',
    projectId: 'agriconnect-9aab3',
    storageBucket: 'agriconnect-9aab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSGfHyS6c8nnR0pnIe6gOoi4nwfOXgkA',
    appId: '1:629374223951:ios:7a1c21a120ef4ec6130c3a',
    messagingSenderId: '629374223951',
    projectId: 'agriconnect-9aab3',
    storageBucket: 'agriconnect-9aab3.firebasestorage.app',
    iosBundleId: 'com.example.agriConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSGfHyS6c8nnR0pnIe6gOoi4nwfOXgkA',
    appId: '1:629374223951:ios:7a1c21a120ef4ec6130c3a',
    messagingSenderId: '629374223951',
    projectId: 'agriconnect-9aab3',
    storageBucket: 'agriconnect-9aab3.firebasestorage.app',
    iosBundleId: 'com.example.agriConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBibekW-972BMNCHJpCyHYAcVE2X5e8Tac',
    appId: '1:629374223951:web:d671ba335fcbb3a8130c3a',
    messagingSenderId: '629374223951',
    projectId: 'agriconnect-9aab3',
    authDomain: 'agriconnect-9aab3.firebaseapp.com',
    storageBucket: 'agriconnect-9aab3.firebasestorage.app',
    measurementId: 'G-BH7SQB6VSD',
  );
}
